# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c736965a2b31f016b43914109b4b0ab7"
name = "first-app"
handle = "first-app-1142"
application_url = "https://extreme-earned-preferences-wheels.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "arwin-lb.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://extreme-earned-preferences-wheels.trycloudflare.com/auth/callback",
  "https://extreme-earned-preferences-wheels.trycloudflare.com/auth/shopify/callback",
  "https://extreme-earned-preferences-wheels.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
